### ISSUE TITLE
The v3.3.0 release file formats do not match the file type

### ISSUE THREAD

**Issue by xxxserxxx** [Jacalz/rymdport#59] opened 2023-01-15 14:58 UTC
```
$ curl -sLO https://github.com/Jacalz/rymdport/releases/download/v3.3.0/rymdport-v3.3.0-linux-amd64.zip
$ file rymdport-v3.3.0-linux-amd64.zip
rymdport-v3.3.0-linux-amd64.zip: XZ compressed data, checksum CRC64
$ tar tf rymdport-v3.3.0-linux-amd64.zip
usr/
usr/local/
...
```

**Comment by Jacalz** [comment] 2023-01-15 15:29
Gosh, that's embarrassing. Sorry about that. The issue was bug in the script that I use to rename the files with. The issue is that I am using [Geoffrey](https://fynelabs.com/geoffrey/) for automated builds and their downloads are not yet correctly named after version/architecture. Should be fixed now.

FYI: Please fill out the issue template next time. It greatly helps when triaging issues.

**Closed by Jacalz** 2023-01-15 15:29 UTC
Labels: bug, infrastructure
