### ISSUE TITLE
Build for Android?

### ISSUE THREAD

**Issue by kdpuvvadi** [Jacalz/rymdport#40] opened 2022-06-04 10:09 UTC
### Describe the solution you'd like to see:

is there any plan for releasing a build for android?

**Comment by Jacalz** [comment] 2022-06-04 12:18
There certainly is :)
I have a (albeit ageing and not complete) implementation in the [mobile3](https://github.com/Jacalz/rymdport/tree/mobile3) branch. I plan on doing some small improvement soon that should make the mobile support easier to implement in the future.

It has unfortunately had to be prioritised down due to lack of time (I am studying Computer Science at the university) and [lack of funding](https://github.com/Jacalz/rymdport/tree/mobile3#sponsoring) (basically that I don't have any Android phone and the marketplaces cost money to set up and maintain). But yes, the plan is definitely to support Android and other mobile platforms.

However, I will go ahead and close this as a duplicate of https://github.com/Jacalz/rymdport/issues/19.

**Closed** 2022-06-04 12:19 UTC
Labels: duplicate
