### ISSUE TITLE
Send file by dragging & dropping from Windows explorer/desktop onto send tab

### ISSUE THREAD

**Issue by vlasky** [Jacalz/rymdport#95] opened 2023-08-03 13:23 UTC
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I attempted to drag & drop a file from my Windows 10 desktop onto the Rymdport send tab but this does not appear to be supported. Instead, you have to use "add content to send" and then navigate to the location and select the file.

### Describe the solution you'd like to see.

It would be less tedious to be able to drag and drop the file/icon onto the send tab of Rymdport.

**Comment by Jacalz** [comment] 2023-08-03 15:15
This is a duplicate of https://github.com/Jacalz/rymdport/issues/73. The feature has already been implemented on the `next` branch and will be in the next release.

**Closed** 2023-08-03 15:16 UTC
Labels: duplicate
